### PR TITLE
Fix #73, show the last viewed sidebar page when reopening the sidebar

### LINKED ISSUE #73: The sidebar's Homepage UI is wrongly displayed instead of the previously opened website, after the sidebar is switched or reopened
[Affected versions]:
- Firefox 58.0.2 and up
- Tab Split 2 0.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Tab Split 2 v0.2.0 installed.
- Have the Tab Split sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to a website.
2. Click the tab from the "Current Tabs" section.
3. Change the sidebar to "Bookmarks".
4. Switch back to "Tab Split" and observe the displayed content.

[Expected result]:
- The previously opened website is displayed.

[Actual result]:
- The Tab Split's Homepage UI is displayed.

[Notes]:
- This behavior is already present for the "Bookmarks" and "History" sidebars.
- Here is a screen recording with this issue:
tab split 2 - switch sidebar

### PR DESCRIPTION
**Pull request by ianb**

### CODE REVIEW

File: addon/background.js [hunk 1]
```diff
@@ -64,11 +65,12 @@ browser.browserAction.onClicked.addListener(async () => {
   await openUrl(url);
 });
 
-async function openUrl(url) {
+async function openUrl(url, inWindowId = null) {
   // FIXME: should send something in an event about whether the desktop has already been set
-  const windowInfo = await browser.windows.getCurrent();
+  const windowInfo = {id: inWindowId} || await browser.windows.getCurrent();
```
Comment (fzzzy) [inline addon/background.js]: This doesn't work. {} || "foo" always evaluates to {}. Perhaps `inWindowId !== null ? { id: inWindowId } : await browser.windows.getCurrent()`?

**Comment by ianb** [comment]
Thanks for noticing that bug, second time on that and I still got it wrong :P

I found another bug, fixed in the follow-on commit.
